return {
	a = "com.daymore.Across",
	b = "app.zen-browser.zen",
	c = "dev.zed.Zed",
	d = "com.hnc.Discord",
	f = "com.apple.finder",
	k = "com.kakao.KakaoTalkMac",
	l = "ru.keepcoder.Telegram",
	m = "com.apple.mail",
	n = "notion.id",
	o = "com.microsoft.Outlook",
	s = "com.tinyspeck.slackmacgap",
	t = "com.cmuxterm.app",
	v = "com.google.Chrome",
}
